// <auto-generated />
using System;
using E_learningPlatform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_learningPlatform.Migrations
{
    [DbContext(typeof(ElearnDbContext))]
    [Migration("20250521041740_handlePaths")]
    partial class handlePaths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.Property<int>("CoursesCourseId")
                        .HasColumnType("int");

                    b.Property<Guid>("studentsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CoursesCourseId", "studentsId");

                    b.HasIndex("studentsId");

                    b.ToTable("CourseUser");
                });

            modelBuilder.Entity("E_learningPlatform.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Geography"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 5,
                            Name = "English"
                        });
                });

            modelBuilder.Entity("E_learningPlatform.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.HasKey("CourseId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Available = true,
                            CategoryId = 1,
                            CourseTitle = "Physics 101",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2590),
                            Description = "Introduction to classical mechanics and thermodynamics.",
                            Image = "physics101.jpg",
                            InstructorName = "Mr. Ahmed Adel",
                            Price = 100,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2591)
                        },
                        new
                        {
                            CourseId = 4,
                            Available = true,
                            CategoryId = 1,
                            CourseTitle = "Chemistry Fundamentals",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2599),
                            Description = "Explore the basic principles of chemistry, atoms, and molecules.",
                            Image = "chemistry.jpg",
                            InstructorName = "Dr. Fatima Khalil",
                            Price = 95,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2600)
                        },
                        new
                        {
                            CourseId = 5,
                            Available = true,
                            CategoryId = 1,
                            CourseTitle = "Introduction to Biology",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2604),
                            Description = "Learn about the science of life, from cells to ecosystems.",
                            Image = "biology.jpg",
                            InstructorName = "Prof. Samira Zayd",
                            Price = 110,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2604)
                        },
                        new
                        {
                            CourseId = 6,
                            Available = true,
                            CategoryId = 1,
                            CourseTitle = "Astronomy: Exploring the Cosmos",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2607),
                            Description = "A journey through space, stars, planets, and galaxies.",
                            Image = "astronomy.jpg",
                            InstructorName = "Mr. Karim Farouk",
                            Price = 125,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2608)
                        },
                        new
                        {
                            CourseId = 7,
                            Available = true,
                            CategoryId = 1,
                            CourseTitle = "Environmental Science Basics",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2611),
                            Description = "Understanding human impact on the environment and ecosystems.",
                            Image = "environmental.jpg",
                            InstructorName = "Ms. Layla Ibrahim",
                            Price = 90,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2612)
                        },
                        new
                        {
                            CourseId = 2,
                            Available = true,
                            CategoryId = 2,
                            CourseTitle = "Calculus for Beginners",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2615),
                            Description = "Grasp the fundamentals of differential and integral calculus.",
                            Image = "calculus.jpg",
                            InstructorName = "Mr. Mohamed Ahmed",
                            Price = 80,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2615)
                        },
                        new
                        {
                            CourseId = 8,
                            Available = true,
                            CategoryId = 2,
                            CourseTitle = "Algebra Essentials",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2620),
                            Description = "Master the core concepts of algebra, including equations and functions.",
                            Image = "algebra.jpg",
                            InstructorName = "Ms. Hoda Salah",
                            Price = 75,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2620)
                        },
                        new
                        {
                            CourseId = 9,
                            Available = true,
                            CategoryId = 2,
                            CourseTitle = "Statistics and Probability",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2624),
                            Description = "Learn to analyze data and understand the principles of probability.",
                            Image = "statistics.jpg",
                            InstructorName = "Mr. Tarek Mahmoud",
                            Price = 100,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2625)
                        },
                        new
                        {
                            CourseId = 10,
                            Available = true,
                            CategoryId = 2,
                            CourseTitle = "Geometry: Shapes and Space",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2628),
                            Description = "Explore Euclidean geometry, shapes, proofs, and spatial reasoning.",
                            Image = "geometry.jpg",
                            InstructorName = "Dr. Ibrahim Youssef",
                            Price = 85,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2628)
                        },
                        new
                        {
                            CourseId = 11,
                            Available = false,
                            CategoryId = 2,
                            CourseTitle = "Trigonometry Fundamentals",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2631),
                            Description = "Understand angles, triangles, and trigonometric functions.",
                            Image = "trigonometry.jpg",
                            InstructorName = "Ms. Nadia Hassan",
                            Price = 70,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2632)
                        },
                        new
                        {
                            CourseId = 3,
                            Available = true,
                            CategoryId = 3,
                            CourseTitle = "Introduction to Physical Geography",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2636),
                            Description = "Explore Earth's landforms, climate, and natural processes.",
                            Image = "physical_geography.jpg",
                            InstructorName = "Dr. Hassan Fares",
                            Price = 110,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2637)
                        },
                        new
                        {
                            CourseId = 12,
                            Available = true,
                            CategoryId = 3,
                            CourseTitle = "World Regional Geography",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2640),
                            Description = "A survey of the world's major cultural and physical regions.",
                            Image = "world_regions.jpg",
                            InstructorName = "Prof. Mona Said",
                            Price = 115,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2641)
                        },
                        new
                        {
                            CourseId = 13,
                            Available = true,
                            CategoryId = 3,
                            CourseTitle = "Introduction to GIS",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2644),
                            Description = "Learn the basics of Geographic Information Systems and mapping.",
                            Image = "gis_intro.jpg",
                            InstructorName = "Eng. Karim Ismail",
                            Price = 135,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2644)
                        },
                        new
                        {
                            CourseId = 14,
                            Available = true,
                            CategoryId = 3,
                            CourseTitle = "Urban Geography",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2647),
                            Description = "Study the spatial structure and development of cities.",
                            Image = "urban_geography.jpg",
                            InstructorName = "Dr. Hassan Fares",
                            Price = 120,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2648)
                        },
                        new
                        {
                            CourseId = 15,
                            Available = true,
                            CategoryId = 3,
                            CourseTitle = "Climatology Basics",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2651),
                            Description = "Understanding weather patterns, climate zones, and climate change.",
                            Image = "climatology.jpg",
                            InstructorName = "Ms. Salwa Ali",
                            Price = 110,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2651)
                        },
                        new
                        {
                            CourseId = 16,
                            Available = true,
                            CategoryId = 4,
                            CourseTitle = "Introduction to Python Programming",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2654),
                            Description = "Learn the fundamentals of programming using Python.",
                            Image = "python_intro.jpg",
                            InstructorName = "Eng. Omar Sharif",
                            Price = 150,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2655)
                        },
                        new
                        {
                            CourseId = 17,
                            Available = true,
                            CategoryId = 4,
                            CourseTitle = "Web Development Basics (HTML, CSS, JS)",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2658),
                            Description = "Build your first websites using core web technologies.",
                            Image = "webdev_basics.jpg",
                            InstructorName = "Ms. Reem Abbas",
                            Price = 140,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2658)
                        },
                        new
                        {
                            CourseId = 18,
                            Available = true,
                            CategoryId = 4,
                            CourseTitle = "Cybersecurity Fundamentals",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2661),
                            Description = "Understand the basics of cybersecurity threats and defenses.",
                            Image = "cybersecurity.jpg",
                            InstructorName = "Mr. Ali Mansour",
                            Price = 160,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2662)
                        },
                        new
                        {
                            CourseId = 19,
                            Available = true,
                            CategoryId = 4,
                            CourseTitle = "Data Science Essentials",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2665),
                            Description = "An introduction to data analysis, visualization, and machine learning concepts.",
                            Image = "datascience.jpg",
                            InstructorName = "Dr. Zainab Dawoud",
                            Price = 175,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2665)
                        },
                        new
                        {
                            CourseId = 20,
                            Available = true,
                            CategoryId = 4,
                            CourseTitle = "Cloud Computing with AWS",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2668),
                            Description = "Learn the basics of cloud services using Amazon Web Services.",
                            Image = "aws_cloud.png",
                            InstructorName = "Eng. Rami Said",
                            Price = 180,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2669)
                        },
                        new
                        {
                            CourseId = 21,
                            Available = true,
                            CategoryId = 5,
                            CourseTitle = "English Grammar Essentials",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2672),
                            Description = "Master the core rules of English grammar and punctuation.",
                            Image = "grammar.jpg",
                            InstructorName = "Ms. Sarah Jones",
                            Price = 90,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2674)
                        },
                        new
                        {
                            CourseId = 22,
                            Available = true,
                            CategoryId = 5,
                            CourseTitle = "Creative Writing: Fiction & Poetry",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2677),
                            Description = "Develop your skills in writing compelling stories and poems.",
                            Image = "creative_writing.jpg",
                            InstructorName = "Mr. David Miller",
                            Price = 85,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2677)
                        },
                        new
                        {
                            CourseId = 23,
                            Available = true,
                            CategoryId = 5,
                            CourseTitle = "Advanced English Composition",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2680),
                            Description = "Learn techniques for crafting effective essays and reports.",
                            Image = "composition.jpg",
                            InstructorName = "Dr. Emily White",
                            Price = 95,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2680)
                        },
                        new
                        {
                            CourseId = 24,
                            Available = true,
                            CategoryId = 5,
                            CourseTitle = "Business English Communication",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2683),
                            Description = "Improve your professional writing and speaking skills.",
                            Image = "business_english.jpg",
                            InstructorName = "Mr. John Smith",
                            Price = 110,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2684)
                        },
                        new
                        {
                            CourseId = 25,
                            Available = true,
                            CategoryId = 5,
                            CourseTitle = "Survey of English Literature",
                            CreatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2687),
                            Description = "Explore major authors and works from Old English to Modern.",
                            Image = "english_literature.jpg",
                            InstructorName = "Prof. Laura Brown",
                            Price = 100,
                            UpdatedAt = new DateTime(2025, 5, 21, 4, 17, 39, 527, DateTimeKind.Utc).AddTicks(2687)
                        });
                });

            modelBuilder.Entity("E_learningPlatform.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("courseId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("E_learningPlatform.Models.MyCourse", b =>
                {
                    b.Property<int>("MycourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MycourseId"));

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.HasKey("MycourseId");

                    b.HasIndex("StudentId");

                    b.HasIndex("courseId");

                    b.ToTable("MyCourses");
                });

            modelBuilder.Entity("E_learningPlatform.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("E_learningPlatform.Models.lesson", b =>
                {
                    b.Property<int>("lessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lessonId"));

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.Property<string>("lessonTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lessonVideo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("lessonId");

                    b.HasIndex("courseId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            lessonId = 1,
                            courseId = 1,
                            lessonTitle = "Introduction to Mechanics",
                            lessonVideo = "physics_101_L1.mp4"
                        },
                        new
                        {
                            lessonId = 2,
                            courseId = 1,
                            lessonTitle = "Kinematics and Motion",
                            lessonVideo = "physics_101_L2.mp4"
                        },
                        new
                        {
                            lessonId = 3,
                            courseId = 1,
                            lessonTitle = "Newton's Laws of Motion",
                            lessonVideo = "physics_101_L3.mp4"
                        },
                        new
                        {
                            lessonId = 4,
                            courseId = 1,
                            lessonTitle = "Work, Energy, and Power",
                            lessonVideo = "physics_101_L4.mp4"
                        },
                        new
                        {
                            lessonId = 5,
                            courseId = 1,
                            lessonTitle = "Basics of Thermodynamics",
                            lessonVideo = "physics_101_L5.mp4"
                        },
                        new
                        {
                            lessonId = 6,
                            courseId = 4,
                            lessonTitle = "Atoms, Molecules, and Ions",
                            lessonVideo = "chemistry_L1.mp4"
                        },
                        new
                        {
                            lessonId = 7,
                            courseId = 4,
                            lessonTitle = "Chemical Bonding",
                            lessonVideo = "chemistry_L2.mp4"
                        },
                        new
                        {
                            lessonId = 8,
                            courseId = 4,
                            lessonTitle = "Stoichiometry and Moles",
                            lessonVideo = "chemistry_L3.mp4"
                        },
                        new
                        {
                            lessonId = 9,
                            courseId = 4,
                            lessonTitle = "States of Matter (Gas, Liquid, Solid)",
                            lessonVideo = "chemistry_L4.mp4"
                        },
                        new
                        {
                            lessonId = 10,
                            courseId = 4,
                            lessonTitle = "Types of Chemical Reactions",
                            lessonVideo = "chemistry_L5.mp4"
                        },
                        new
                        {
                            lessonId = 11,
                            courseId = 5,
                            lessonTitle = "The Science of Life and The Cell",
                            lessonVideo = "biology_L1.mp4"
                        },
                        new
                        {
                            lessonId = 12,
                            courseId = 5,
                            lessonTitle = "Genetics and DNA",
                            lessonVideo = "biology_L2.mp4"
                        },
                        new
                        {
                            lessonId = 13,
                            courseId = 5,
                            lessonTitle = "Evolution and Natural Selection",
                            lessonVideo = "biology_L3.mp4"
                        },
                        new
                        {
                            lessonId = 14,
                            courseId = 5,
                            lessonTitle = "Introduction to Ecology",
                            lessonVideo = "biology_L4.mp4"
                        },
                        new
                        {
                            lessonId = 15,
                            courseId = 5,
                            lessonTitle = "Human Anatomy Overview",
                            lessonVideo = "biology_L5.mp4"
                        },
                        new
                        {
                            lessonId = 16,
                            courseId = 6,
                            lessonTitle = "Our Solar System",
                            lessonVideo = "astronomy_L1.mp4"
                        },
                        new
                        {
                            lessonId = 17,
                            courseId = 6,
                            lessonTitle = "Stars, Nebulae, and Galaxies",
                            lessonVideo = "astronomy_L2.mp4"
                        },
                        new
                        {
                            lessonId = 18,
                            courseId = 6,
                            lessonTitle = "The Big Bang and Cosmology",
                            lessonVideo = "astronomy_L3.mp4"
                        },
                        new
                        {
                            lessonId = 19,
                            courseId = 6,
                            lessonTitle = "Telescopes and Observation",
                            lessonVideo = "astronomy_L4.mp4"
                        },
                        new
                        {
                            lessonId = 20,
                            courseId = 6,
                            lessonTitle = "The Future of Space Exploration",
                            lessonVideo = "astronomy_L5.mp4"
                        },
                        new
                        {
                            lessonId = 21,
                            courseId = 7,
                            lessonTitle = "Introduction to Ecosystems",
                            lessonVideo = "env_science_L1.mp4"
                        },
                        new
                        {
                            lessonId = 22,
                            courseId = 7,
                            lessonTitle = "Pollution and Its Effects",
                            lessonVideo = "env_science_L2.mp4"
                        },
                        new
                        {
                            lessonId = 23,
                            courseId = 7,
                            lessonTitle = "Biodiversity and Conservation",
                            lessonVideo = "env_science_L3.mp4"
                        },
                        new
                        {
                            lessonId = 24,
                            courseId = 7,
                            lessonTitle = "Understanding Climate Change",
                            lessonVideo = "env_science_L4.mp4"
                        },
                        new
                        {
                            lessonId = 25,
                            courseId = 7,
                            lessonTitle = "Sustainable Practices",
                            lessonVideo = "env_science_L5.mp4"
                        },
                        new
                        {
                            lessonId = 26,
                            courseId = 2,
                            lessonTitle = "Introduction to Limits",
                            lessonVideo = "calculus_L1.mp4"
                        },
                        new
                        {
                            lessonId = 27,
                            courseId = 2,
                            lessonTitle = "Derivatives and Differentiation Rules",
                            lessonVideo = "calculus_L2.mp4"
                        },
                        new
                        {
                            lessonId = 28,
                            courseId = 2,
                            lessonTitle = "Applications of Derivatives",
                            lessonVideo = "calculus_L3.mp4"
                        },
                        new
                        {
                            lessonId = 29,
                            courseId = 2,
                            lessonTitle = "Introduction to Integrals",
                            lessonVideo = "calculus_L4.mp4"
                        },
                        new
                        {
                            lessonId = 30,
                            courseId = 2,
                            lessonTitle = "The Fundamental Theorem of Calculus",
                            lessonVideo = "calculus_L5.mp4"
                        },
                        new
                        {
                            lessonId = 31,
                            courseId = 8,
                            lessonTitle = "Real Numbers and Operations",
                            lessonVideo = "algebra_L1.mp4"
                        },
                        new
                        {
                            lessonId = 32,
                            courseId = 8,
                            lessonTitle = "Solving Linear Equations and Inequalities",
                            lessonVideo = "algebra_L22.mp4"
                        },
                        new
                        {
                            lessonId = 33,
                            courseId = 8,
                            lessonTitle = "Polynomials and Factoring",
                            lessonVideo = "algebra_L3.mp4"
                        },
                        new
                        {
                            lessonId = 34,
                            courseId = 8,
                            lessonTitle = "Rational Expressions",
                            lessonVideo = "algebra_L4.mp4"
                        },
                        new
                        {
                            lessonId = 35,
                            courseId = 8,
                            lessonTitle = "Functions and Graphs",
                            lessonVideo = "algebra_L5.mp4"
                        },
                        new
                        {
                            lessonId = 36,
                            courseId = 9,
                            lessonTitle = "Introduction to Statistics and Data",
                            lessonVideo = "statistics_L1.mp4"
                        },
                        new
                        {
                            lessonId = 37,
                            courseId = 9,
                            lessonTitle = "Descriptive Statistics (Mean, Median, Mode)",
                            lessonVideo = "statistics_L2.mp4"
                        },
                        new
                        {
                            lessonId = 38,
                            courseId = 9,
                            lessonTitle = "Basic Probability Concepts",
                            lessonVideo = "statistics_L3.mp4"
                        },
                        new
                        {
                            lessonId = 39,
                            courseId = 9,
                            lessonTitle = "Discrete and Continuous Distributions",
                            lessonVideo = "statistics_L4.mp4"
                        },
                        new
                        {
                            lessonId = 40,
                            courseId = 9,
                            lessonTitle = "Introduction to Hypothesis Testing",
                            lessonVideo = "statistics_L5.mp4"
                        },
                        new
                        {
                            lessonId = 41,
                            courseId = 10,
                            lessonTitle = "Points, Lines, Angles, and Planes",
                            lessonVideo = "geometry_L1.mp4"
                        },
                        new
                        {
                            lessonId = 42,
                            courseId = 10,
                            lessonTitle = "Triangles and Their Properties",
                            lessonVideo = "geometry_L2.mp4"
                        },
                        new
                        {
                            lessonId = 43,
                            courseId = 10,
                            lessonTitle = "Quadrilaterals and Polygons",
                            lessonVideo = "geometry_L3.mp4"
                        },
                        new
                        {
                            lessonId = 44,
                            courseId = 10,
                            lessonTitle = "Circles",
                            lessonVideo = "geometry_L4.mp4"
                        },
                        new
                        {
                            lessonId = 45,
                            courseId = 10,
                            lessonTitle = "Area, Perimeter, and Volume",
                            lessonVideo = "geometry_L5.mp4"
                        },
                        new
                        {
                            lessonId = 46,
                            courseId = 11,
                            lessonTitle = "Angles and Radian Measure",
                            lessonVideo = "trigonometry_L1.mp4"
                        },
                        new
                        {
                            lessonId = 47,
                            courseId = 11,
                            lessonTitle = "Right Triangle Trigonometry (SOH CAH TOA)",
                            lessonVideo = "trigonometry_L2.mp4"
                        },
                        new
                        {
                            lessonId = 48,
                            courseId = 11,
                            lessonTitle = "The Unit Circle",
                            lessonVideo = "trigonometry_L3.mp4"
                        },
                        new
                        {
                            lessonId = 49,
                            courseId = 11,
                            lessonTitle = "Graphs of Trigonometric Functions",
                            lessonVideo = "trigonometry_L4.mp4"
                        },
                        new
                        {
                            lessonId = 50,
                            courseId = 11,
                            lessonTitle = "Basic Trigonometric Identities",
                            lessonVideo = "trigonometry_L5.mp4"
                        },
                        new
                        {
                            lessonId = 51,
                            courseId = 3,
                            lessonTitle = "What is Physical Geography?",
                            lessonVideo = "phys_geo_L1.mp4"
                        },
                        new
                        {
                            lessonId = 52,
                            courseId = 3,
                            lessonTitle = "Earth's Atmosphere and Weather",
                            lessonVideo = "phys_geo_L2.mp4"
                        },
                        new
                        {
                            lessonId = 53,
                            courseId = 3,
                            lessonTitle = "Landforms and Geomorphology",
                            lessonVideo = "phys_geo_L3.mp4"
                        },
                        new
                        {
                            lessonId = 54,
                            courseId = 3,
                            lessonTitle = "Water Systems: Oceans and Rivers",
                            lessonVideo = "phys_geo_L4.mp4"
                        },
                        new
                        {
                            lessonId = 55,
                            courseId = 3,
                            lessonTitle = "Biogeography and Ecosystems",
                            lessonVideo = "phys_geo_L5.mp4"
                        },
                        new
                        {
                            lessonId = 56,
                            courseId = 12,
                            lessonTitle = "Introduction to Regions",
                            lessonVideo = "world_regions_L1.mp4"
                        },
                        new
                        {
                            lessonId = 57,
                            courseId = 12,
                            lessonTitle = "North and South America",
                            lessonVideo = "world_regions_L2.mp4"
                        },
                        new
                        {
                            lessonId = 58,
                            courseId = 12,
                            lessonTitle = "Europe and Russia",
                            lessonVideo = "world_regions_L3.mp4"
                        },
                        new
                        {
                            lessonId = 59,
                            courseId = 12,
                            lessonTitle = "Asia and the Middle East",
                            lessonVideo = "world_regions_L4.mp4"
                        },
                        new
                        {
                            lessonId = 60,
                            courseId = 12,
                            lessonTitle = "Africa and Oceania",
                            lessonVideo = "world_regions_L5.mp4"
                        },
                        new
                        {
                            lessonId = 61,
                            courseId = 13,
                            lessonTitle = "What is GIS and Spatial Data?",
                            lessonVideo = "gis_L1.mp4"
                        },
                        new
                        {
                            lessonId = 62,
                            courseId = 13,
                            lessonTitle = "Vector and Raster Data Models",
                            lessonVideo = "gis_L2.mp4"
                        },
                        new
                        {
                            lessonId = 63,
                            courseId = 13,
                            lessonTitle = "Basic Spatial Analysis",
                            lessonVideo = "gis_L3.mp4"
                        },
                        new
                        {
                            lessonId = 64,
                            courseId = 13,
                            lessonTitle = "Map Projections and Coordinate Systems",
                            lessonVideo = "gis_L4.mp4"
                        },
                        new
                        {
                            lessonId = 65,
                            courseId = 13,
                            lessonTitle = "Introduction to Cartography and Map Design",
                            lessonVideo = "gis_L5.mp4"
                        },
                        new
                        {
                            lessonId = 66,
                            courseId = 14,
                            lessonTitle = "The Study of Cities",
                            lessonVideo = "urban_geo_L1.mp4"
                        },
                        new
                        {
                            lessonId = 67,
                            courseId = 14,
                            lessonTitle = "Urbanization and City Origins",
                            lessonVideo = "urban_geo_L2.mp4"
                        },
                        new
                        {
                            lessonId = 68,
                            courseId = 14,
                            lessonTitle = "Internal Structure of Cities (Models)",
                            lessonVideo = "urban_geo_L3.mp4"
                        },
                        new
                        {
                            lessonId = 69,
                            courseId = 14,
                            lessonTitle = "Urban Challenges (Housing, Transport)",
                            lessonVideo = "urban_geo_L4.mp4"
                        },
                        new
                        {
                            lessonId = 70,
                            courseId = 14,
                            lessonTitle = "Global Cities and Future Urban Trends",
                            lessonVideo = "urban_geo_L5.mp4"
                        },
                        new
                        {
                            lessonId = 71,
                            courseId = 15,
                            lessonTitle = "Earth's Climate System",
                            lessonVideo = "climatology_L1.mp4"
                        },
                        new
                        {
                            lessonId = 72,
                            courseId = 15,
                            lessonTitle = "Atmospheric Circulation",
                            lessonVideo = "climatology_L2.mp4"
                        },
                        new
                        {
                            lessonId = 73,
                            courseId = 15,
                            lessonTitle = "World Climate Zones (Koppen System)",
                            lessonVideo = "climatology_L3.mp4"
                        },
                        new
                        {
                            lessonId = 74,
                            courseId = 15,
                            lessonTitle = "Climate Change: Causes and Impacts",
                            lessonVideo = "climatology_L4.mp4"
                        },
                        new
                        {
                            lessonId = 75,
                            courseId = 15,
                            lessonTitle = "Paleoclimatology (Past Climates)",
                            lessonVideo = "climatology_L5.mp4"
                        },
                        new
                        {
                            lessonId = 76,
                            courseId = 16,
                            lessonTitle = "Introduction and Setup",
                            lessonVideo = "python_L1.mp4"
                        },
                        new
                        {
                            lessonId = 77,
                            courseId = 16,
                            lessonTitle = "Variables, Data Types, and Operators",
                            lessonVideo = "python_L2.mp4"
                        },
                        new
                        {
                            lessonId = 78,
                            courseId = 16,
                            lessonTitle = "Control Flow (If, Loops)",
                            lessonVideo = "python_L3.mp4"
                        },
                        new
                        {
                            lessonId = 79,
                            courseId = 16,
                            lessonTitle = "Functions and Modules",
                            lessonVideo = "python_L4.mp4"
                        },
                        new
                        {
                            lessonId = 80,
                            courseId = 16,
                            lessonTitle = "Basic Data Structures (Lists, Dictionaries)",
                            lessonVideo = "python_L5.mp4"
                        },
                        new
                        {
                            lessonId = 81,
                            courseId = 17,
                            lessonTitle = "Introduction to HTML",
                            lessonVideo = "webdev_L1.mp4"
                        },
                        new
                        {
                            lessonId = 82,
                            courseId = 17,
                            lessonTitle = "Styling with CSS",
                            lessonVideo = "webdev_L2.mp4"
                        },
                        new
                        {
                            lessonId = 83,
                            courseId = 17,
                            lessonTitle = "CSS Box Model and Layouts",
                            lessonVideo = "webdev_L3.mp4"
                        },
                        new
                        {
                            lessonId = 84,
                            courseId = 17,
                            lessonTitle = "Introduction to JavaScript",
                            lessonVideo = "webdev_L4.mp4"
                        },
                        new
                        {
                            lessonId = 85,
                            courseId = 17,
                            lessonTitle = "JavaScript DOM Manipulation",
                            lessonVideo = "webdev_L5.mp4"
                        },
                        new
                        {
                            lessonId = 86,
                            courseId = 18,
                            lessonTitle = "Introduction to Cybersecurity Threats",
                            lessonVideo = "cybersecurity_L1.mp4"
                        },
                        new
                        {
                            lessonId = 87,
                            courseId = 18,
                            lessonTitle = "Network Security Basics",
                            lessonVideo = "cybersecurity_L2.mp4"
                        },
                        new
                        {
                            lessonId = 88,
                            courseId = 18,
                            lessonTitle = "Cryptography Essentials",
                            lessonVideo = "cybersecurity_L3.mp4"
                        },
                        new
                        {
                            lessonId = 89,
                            courseId = 18,
                            lessonTitle = "Web Application Security",
                            lessonVideo = "cybersecurity_L4.mp4"
                        },
                        new
                        {
                            lessonId = 90,
                            courseId = 18,
                            lessonTitle = "Security Policies and Best Practices",
                            lessonVideo = "cybersecurity_L5.mp4"
                        },
                        new
                        {
                            lessonId = 91,
                            courseId = 19,
                            lessonTitle = "What is Data Science?",
                            lessonVideo = "datascience_L1.mp4"
                        },
                        new
                        {
                            lessonId = 92,
                            courseId = 19,
                            lessonTitle = "Data Acquisition and Cleaning",
                            lessonVideo = "datascience_L2.mp4"
                        },
                        new
                        {
                            lessonId = 93,
                            courseId = 19,
                            lessonTitle = "Exploratory Data Analysis (EDA)",
                            lessonVideo = "datascience_L3.mp4"
                        },
                        new
                        {
                            lessonId = 94,
                            courseId = 19,
                            lessonTitle = "Introduction to Machine Learning Concepts",
                            lessonVideo = "datascience_L4.mp4"
                        },
                        new
                        {
                            lessonId = 95,
                            courseId = 19,
                            lessonTitle = "Data Visualization Techniques",
                            lessonVideo = "datascience_L5.mp4"
                        },
                        new
                        {
                            lessonId = 96,
                            courseId = 20,
                            lessonTitle = "Introduction to Cloud Computing and AWS",
                            lessonVideo = "aws_cloud_L1.mp4"
                        },
                        new
                        {
                            lessonId = 97,
                            courseId = 20,
                            lessonTitle = "Core AWS Services (EC2, S3)",
                            lessonVideo = "aws_cloud_L2.mp4"
                        },
                        new
                        {
                            lessonId = 98,
                            courseId = 20,
                            lessonTitle = "AWS Networking (VPC)",
                            lessonVideo = "aws_cloud_L3.mp4"
                        },
                        new
                        {
                            lessonId = 99,
                            courseId = 20,
                            lessonTitle = "AWS Databases (RDS, DynamoDB)",
                            lessonVideo = "aws_cloud_L4.mp4"
                        },
                        new
                        {
                            lessonId = 100,
                            courseId = 20,
                            lessonTitle = "AWS Security and IAM",
                            lessonVideo = "aws_cloud_L5.mp4"
                        },
                        new
                        {
                            lessonId = 101,
                            courseId = 21,
                            lessonTitle = "Parts of Speech (Nouns, Verbs, Adjectives)",
                            lessonVideo = "grammar_L1.mp4"
                        },
                        new
                        {
                            lessonId = 102,
                            courseId = 21,
                            lessonTitle = "Sentence Structure (Subjects, Predicates, Clauses)",
                            lessonVideo = "grammar_L2.mp4"
                        },
                        new
                        {
                            lessonId = 103,
                            courseId = 21,
                            lessonTitle = "Verb Tenses and Forms",
                            lessonVideo = "grammar_L3.mp4"
                        },
                        new
                        {
                            lessonId = 104,
                            courseId = 21,
                            lessonTitle = "Punctuation (Commas, Semicolons, Apostrophes)",
                            lessonVideo = "grammar_L4.mp4"
                        },
                        new
                        {
                            lessonId = 105,
                            courseId = 21,
                            lessonTitle = "Common Grammatical Errors",
                            lessonVideo = "grammar_L5.mp4"
                        },
                        new
                        {
                            lessonId = 106,
                            courseId = 22,
                            lessonTitle = "Finding Inspiration and Ideas",
                            lessonVideo = "creative_write_L1.mp4"
                        },
                        new
                        {
                            lessonId = 107,
                            courseId = 22,
                            lessonTitle = "Character Development",
                            lessonVideo = "creative_write_L2.mp4"
                        },
                        new
                        {
                            lessonId = 108,
                            courseId = 22,
                            lessonTitle = "Plotting and Story Structure",
                            lessonVideo = "creative_write_L3.mp4"
                        },
                        new
                        {
                            lessonId = 109,
                            courseId = 22,
                            lessonTitle = "Writing Vivid Descriptions and Settings",
                            lessonVideo = "creative_write_L4.mp4"
                        },
                        new
                        {
                            lessonId = 110,
                            courseId = 22,
                            lessonTitle = "Introduction to Poetic Forms",
                            lessonVideo = "creative_write_L5.mp4"
                        },
                        new
                        {
                            lessonId = 111,
                            courseId = 23,
                            lessonTitle = "Understanding the Writing Process",
                            lessonVideo = "composition_L1.mp4"
                        },
                        new
                        {
                            lessonId = 112,
                            courseId = 23,
                            lessonTitle = "Crafting Strong Thesis Statements",
                            lessonVideo = "composition_L2.mp4"
                        },
                        new
                        {
                            lessonId = 113,
                            courseId = 23,
                            lessonTitle = "Developing Effective Paragraphs",
                            lessonVideo = "composition_L3.mp4"
                        },
                        new
                        {
                            lessonId = 114,
                            courseId = 23,
                            lessonTitle = "Argumentation and Persuasion",
                            lessonVideo = "composition_L4.mp4"
                        },
                        new
                        {
                            lessonId = 115,
                            courseId = 23,
                            lessonTitle = "Research, Citation, and Avoiding Plagiarism",
                            lessonVideo = "composition_L5.mp4"
                        },
                        new
                        {
                            lessonId = 116,
                            courseId = 24,
                            lessonTitle = "Professional Email Etiquette",
                            lessonVideo = "business_english_L1.mp4"
                        },
                        new
                        {
                            lessonId = 117,
                            courseId = 24,
                            lessonTitle = "Writing Effective Memos and Reports",
                            lessonVideo = "business_english_L2.mp4"
                        },
                        new
                        {
                            lessonId = 118,
                            courseId = 24,
                            lessonTitle = "Delivering Engaging Presentations",
                            lessonVideo = "business_english_L3.mp4"
                        },
                        new
                        {
                            lessonId = 119,
                            courseId = 24,
                            lessonTitle = "Language for Meetings and Negotiations",
                            lessonVideo = "business_english_L4.mp4"
                        },
                        new
                        {
                            lessonId = 120,
                            courseId = 24,
                            lessonTitle = "Cross-Cultural Communication",
                            lessonVideo = "business_english_L5.mp4"
                        },
                        new
                        {
                            lessonId = 121,
                            courseId = 25,
                            lessonTitle = "Old English and Medieval Literature (Beowulf, Chaucer)",
                            lessonVideo = "eng_lit_L1.mp4"
                        },
                        new
                        {
                            lessonId = 122,
                            courseId = 25,
                            lessonTitle = "The Renaissance (Shakespeare, Marlowe)",
                            lessonVideo = "eng_lit_L2.mp4"
                        },
                        new
                        {
                            lessonId = 123,
                            courseId = 25,
                            lessonTitle = "18th and 19th Century Literature (Austen, Dickens)",
                            lessonVideo = "eng_lit_L3.mp4"
                        },
                        new
                        {
                            lessonId = 124,
                            courseId = 25,
                            lessonTitle = "Modernism (Woolf, Eliot, Joyce)",
                            lessonVideo = "eng_lit_L4.mp4"
                        },
                        new
                        {
                            lessonId = 125,
                            courseId = 25,
                            lessonTitle = "Contemporary Literature and Trends",
                            lessonVideo = "eng_lit_L5.mp4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CourseUser", b =>
                {
                    b.HasOne("E_learningPlatform.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_learningPlatform.Models.User", null)
                        .WithMany()
                        .HasForeignKey("studentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_learningPlatform.Models.Course", b =>
                {
                    b.HasOne("E_learningPlatform.Models.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("E_learningPlatform.Models.Enrollment", b =>
                {
                    b.HasOne("E_learningPlatform.Models.User", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_learningPlatform.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("E_learningPlatform.Models.MyCourse", b =>
                {
                    b.HasOne("E_learningPlatform.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_learningPlatform.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("E_learningPlatform.Models.lesson", b =>
                {
                    b.HasOne("E_learningPlatform.Models.Course", "Course")
                        .WithMany("lessons")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("E_learningPlatform.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("E_learningPlatform.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_learningPlatform.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("E_learningPlatform.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("E_learningPlatform.Models.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("E_learningPlatform.Models.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("lessons");
                });

            modelBuilder.Entity("E_learningPlatform.Models.User", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
